//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.26 at 11:41:43 AM CAT 
//


package org.uci.opus.ucm.web.service;

public enum FileModelEnum {

    STANDARD_PAUTA("STANDARD_PAUTA"),
    CED_PAUTA("CED_PAUTA"),
    CED_EXAM_MACHINE("CED_EXAM_MACHINE");
    
    private final String value;

    FileModelEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileModelEnum fromValue(String v) {
        for (FileModelEnum c: FileModelEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

	public String getValue() {
		return value;
	}

}
